apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sleep-info.yaml

# Customize these values as needed
namePrefix: app-
namespace: default-namespace

# Configure sleep schedule values
patchesJson6902:
- target:
    group: kube-green.com
    version: v1alpha1
    kind: SleepInfo
    name: sleep-schedule
  patch: |
    - op: replace
      path: /spec/weekdays
      value: "1-5"
    - op: replace
      path: /spec/sleepAt
      value: "20:00"
    - op: replace
      path: /spec/wakeUpAt
      value: "08:00"
    - op: replace
      path: /spec/timeZone
      value: "Europe/Rome"
