apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: sleep-schedule
spec:
  weekdays: "1-5"
  sleepAt: "19:00"
  wakeUpAt: "07:00" 
  timeZone: "Europe/Rome"
  patches:
    - target:
        group: "apps.openshift.io"
        version: "v1"
        kind: "DeploymentConfig"
      patchStrategy: "scale"
      patchPath: "/spec/replicas"
